#!/bin/sh

SERIAL_HEX=`cat /sys/fsl_otp/HW_OCOTP_GP1`
SERIAL_DEC=`echo $(($SERIAL_HEX))`
TYPE_HEX=`cat /sys/fsl_otp/HW_OCOTP_GP2`
POLYOS_SERVICE="/etc/avahi/services/polyos.service"
POLYOS_VERSION=`cat /polyos_version`

if [ ! -b "/dev/mmcblk1p3" ]; then

cat << EOF | fdisk /dev/mmcblk1
o
n
p
1
24576
+1500M
n
n
p
2
3096580
+1500M
n
p
3
6168580

w
q
EOF
sleep 3
rm -rf /mnt/data
reboot
exit 0
fi

if [ ! -d "/mnt/data" ]; then

    resize2fs -p /dev/mmcblk1p1
    mkfs.ext4 -F /dev/mmcblk1p2
    mkfs.ext4 -F /dev/mmcblk1p3
    sleep 2
    echo "/dev/mmcblk1p3       /mnt/data          ext4       defaults  0  0" >> /etc/fstab
    mkdir -p /mnt/data
    sleep 2
    reboot
    exit 0
fi

if grep -qs grep -qs '/mnt/data ' /proc/mounts; then
    echo "It's mounted."
else
    rm -rf /mnt/data
    mkdir -p /mnt/data
    mount /dev/mmcblk1p3 /mnt/data
fi

if ! [ -d "/mnt/data/settings/wireless/connman" ]; then

        mkdir -p /mnt/data/settings/wireless/connman
        rm -r /var/lib/connman
fi
if ! [ -d "/mnt/data/settings/audio/alsa" ]; then

        mkdir -p /mnt/data/settings/audio/alsa
	touch /mnt/data/settings/audio/alsa/asound.conf
	echo "ctl.!default {" > /mnt/data/settings/audio/alsa/asound.conf
	echo "type hw" >> /mnt/data/settings/audio/alsa/asound.conf
	echo "card 0" >> /mnt/data/settings/audio/alsa/asound.conf
	echo "}" >> /mnt/data/settings/audio/alsa/asound.conf
	echo "pcm.!default {" >> /mnt/data/settings/audio/alsa/asound.conf
	echo "type hw" >> /mnt/data/settings/audio/alsa/asound.conf
	echo "card 0" >> /mnt/data/settings/audio/alsa/asound.conf
	echo "}" >> /mnt/data/settings/audio/alsa/asound.conf
        rm -r /etc/asound.conf
	
fi

if ! [ -d "/mnt/data/appcache/slimserver" ]; then

    mkdir -p /mnt/data/appcache/slimserver/Cache
    mkdir -p /mnt/data/appcache/slimserver/prefs
    mkdir -p /mnt/data/appcache/slimserver/Logs
    rm -rf /usr/bin/slimserver/Cache
    rm -rf /usr/bin/slimserver/prefs
    rm -rf /usr/bin/slimserver/Logs
    ln -s -f /mnt/data/appcache/slimserver/Cache /usr/bin/slimserver/Cache
    ln -s -f /mnt/data/appcache/slimserver/prefs /usr/bin/slimserver/prefs
    ln -s -f /mnt/data/appcache/slimserver/Logs /usr/bin/slimserver/Logs
    chown -R squeezeboxserver /mnt/data/appcache/slimserver
    chgrp -R nogroup /mnt/data/appcache/slimserver
    chown -h squeezeboxserver:nogroup /usr/bin/slimserver/prefs
    chown -h squeezeboxserver:nogroup /usr/bin/slimserver/Cache
    chown -h squeezeboxserver:nogroup /usr/bin/slimserver/Logs

fi

if ! [ -L "/usr/bin/slimserver/Cache" ]; then

    rm -rf /usr/bin/slimserver/Cache
    rm -rf /usr/bin/slimserver/prefs
    rm -rf /usr/bin/slimserver/Logs
    ln -s -f /mnt/data/appcache/slimserver/Cache /usr/bin/slimserver/Cache
    ln -s -f /mnt/data/appcache/slimserver/prefs /usr/bin/slimserver/prefs
    ln -s -f /mnt/data/appcache/slimserver/Logs /usr/bin/slimserver/Logs
    chown -R squeezeboxserver /mnt/data/appcache/slimserver
    chgrp -R nogroup /mnt/data/appcache/slimserver
    chown -h squeezeboxserver:nogroup /usr/bin/slimserver/prefs
    chown -h squeezeboxserver:nogroup /usr/bin/slimserver/Cache
    chown -h squeezeboxserver:nogroup /usr/bin/slimserver/Logs

fi

if ! [ -d "/mnt/data/settings/system" ]; then

        mkdir -p /mnt/data/settings/system
	echo "VoltaStream-$SERIAL_DEC" > /mnt/data/settings/system/hostname
fi

setting_host=`cat /mnt/data/settings/system/hostname`
etc_host=`cat /etc/hostname`

if [ "$etc_host" != "$setting_host" ]; then
	echo "$setting_host" > /etc/hostname
	sed -i '/^device_name/d' /etc/spotifyd.conf
    	echo "device_name = $setting_host" >> /etc/spotifyd.conf
	reboot
    exit 0
fi



if [ ! -f "$POLYOS_SERVICE" ]; then                                        
                                                                           
        echo '<?xml version="1.0" standalone="no"?>' > $POLYOS_SERVICE     
        echo '<!DOCTYPE service-group SYSTEM "avahi-service.dtd">' >> $POLYOS_SERVICE
        echo '<service-group>' >> $POLYOS_SERVICE                               
        echo '<name replace-wildcards="yes">%h</name>' >> $POLYOS_SERVICE       
        echo '<service>' >> $POLYOS_SERVICE                                     
        echo '<type>_polyos._tcp</type>' >> $POLYOS_SERVICE                     
        echo '<port>8080</port>' >> $POLYOS_SERVICE                             
        echo '<txt-record>type='$TYPE_HEX'</txt-record>' >> $POLYOS_SERVICE     
        echo '<txt-record>serial='$SERIAL_DEC'</txt-record>' >> $POLYOS_SERVICE
        echo '<txt-record>os='$POLYOS_VERSION'</txt-record>' >> $POLYOS_SERVICE
        echo '</service>' >> $POLYOS_SERVICE                                    
        echo '</service-group>' >> $POLYOS_SERVICE                              
                                                                                
fi 

mkdir /run/lock
rm -r /var/lib/connman
rm -r /etc/asound.conf
ln -s -f /mnt/data/settings/audio/alsa/asound.conf /etc/asound.conf
ln -s -f /mnt/data/settings/wireless/connman /var/lib/connman

